name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 35.0.0

      # Build the project
      - name: Build Project
        run: ./gradlew assembleDebug

      # Run tests
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Run UI tests (need connected devices)
#      - name: Run UI Tests
#        run: ./gradlew connectedDebugAndroidTest